### ISSUE TITLE
health metrics for service instances

### ISSUE THREAD

**Issue by seilc1** [swisscom/open-service-broker#107]
For billing and  SLA reasons it must be possible to retrieve informations about a service if it is currently running correctly and therefor be billed. For this requirement a simple OK/NOK would be enough. For future implementation it may also be interesting to pass some additional informations about the health of the service (e.g. disk usage, free usage ...).

idea:

`/v2/service_instances/{serviceInstanceGuid}/health`

returns:
`{
	"status": (ok|nok|undefined),
	"metrics": [
		{"property": "cpu-usage", "value": "17", "unit": "percentage" }
	]
}`

as default it will return:

`{
  "status": "undefined",
  "metrics": []
}`

To have a custom health result the interface *ServiceHealthProvider" has to be implemented on the ServiceProvider Implementation.

# Links
- [Latest Service Broker API Spec](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md)

**Comment by MatthiasWinzeler** [comment]
@seilc1 I'm not sure we should mix usage and health, is there a reason to not keep it separate?

**Comment by seilc1** [comment]
my idea is to provide metrics related to health ... e.g. if cpu usage is at 100% this is a bad sign for the health. Or maybe an exception counter? last backup done? this would allow us to monitor services and generate alerts based on these informations.

**Comment by MatthiasWinzeler** [comment]
Good idea, but it is currently not planned to expose metrics like this; the thing is, shipping metrics (and probably also logs) is a quite tricky thing (we call it service insights, @ampersand8 looks at it for his thesis) which will most likely require a different architecture pattern (i.e. shipping metrics and logs over kafka instead of being polled over a GET endpoint).

In true spirit of [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it), I think we should only add it if we need it :)

**Comment by seilc1** [comment]
agreed
